__default__:
    h_vmem: 4G
    tmem: 4G
    h_rt: 2:00:00
    submission_string: " "
bam_to_fastq:
    submission_string: " "
    h_vmem: 8G
    tmem: 8G
    h_rt: 72:00:00
generate_genome:
    submission_string: "-pe smp 4 -R y"
    h_vmem: 8G
    tmem: 8G
    h_rt: 72:00:00
run_star_se:
    submission_string: "-pe smp 4 -R y"
    h_vmem: 8G
    tmem: 8G
    h_rt: 72:00:00
run_tectool:
    submission_string: " "
    h_vmem: 10G
    tmem: 10G
    h_rt: 72:00:00
